services:
  scheduler:
    user: root
    volumes:
      - ./airflow/include:/usr/local/airflow/include
      - ./airflow/dags:/usr/local/airflow/dags
      - ./airflow/plugins:/usr/local/airflow/plugins
