services:
  scheduler:
    user: root
    volumes:
      - ./include:/usr/local/airflow/include
      - ./dags:/usr/local/airflow/dags
      - ./plugins:/usr/local/airflow/plugins

  metabase:
    image: metabase/metabase
    container_name: metabase
    ports:
      - "3000:3000"
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
    volumes:
      - ./metabase-data:/metabase-data
