services:
  scheduler:
    user: root
    volumes:
      - ./include:/usr/local/airflow/include
  
  minio:
    build:
      context: .
      dockerfile: Dockerfile.minio
    container_name: minio
    expose:
      - 9000
      - 9001
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "minioadmin"
    command: ["server", "/data", "--console-address", ":9001"]
    volumes:
      - minio_data:/data
    networks:
      - basketball-dbt-snowflake_554bef_airflow

volumes:
  minio_data:
    driver: local
    
networks:
  basketball-dbt-snowflake_554bef_airflow:
    external: true