name: Run dbt test

on:
  push:
    branches: [feature/*]
    paths:
      - dags/dbt/s3_snowflake_dbt/**
  pull_request:
    branches: [main]

jobs:
  dbt-test:
    runs-on: ubuntu-latest

    env:
      SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
      SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
      SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_DATABASE: "API_DB"
      SNOWFLAKE_SCHEMA: "API_SCHEMA"
      SNOWFLAKE_WAREHOUSE: "API_WH"
      SNOWFLAKE_ROLE: "API_ROLE"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dbt and dependencies
        run: |
          pip install dbt-snowflake==1.8.0

      - name: Create dbt profile
        run: |
          mkdir -p ~/.dbt
          cat > ~/.dbt/profiles.yml <<EOF
          s3_snowflake_dbt:
            target: dev
            outputs:
              dev:
                type: snowflake
                account: $SNOWFLAKE_ACCOUNT
                user: $SNOWFLAKE_USER
                password: $SNOWFLAKE_PASSWORD
                role: $SNOWFLAKE_ROLE
                database: $SNOWFLAKE_DATABASE
                warehouse: $SNOWFLAKE_WAREHOUSE
                schema: $SNOWFLAKE_SCHEMA
                threads: 1
          EOF

      - name: Run dbt deps
        run: dbt deps --project-dir dags/dbt/s3_snowflake_dbt

      - name: dbt compile
        run: dbt compile --project-dir dags/dbt/s3_snowflake_dbt

      - name: Run dbt tests
        run: dbt test --project-dir dags/dbt/s3_snowflake_dbt
